// <auto-generated />
namespace KeepEverything.RaysaDutra.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StartDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StartDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201705290151510_StartDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
